server:
  port: 8080

spring:
  mvc:
    log-request-details: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/realworld
    username: postgres
    password: postgres


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

pd:
  jwt:
    secret: w845w347fh45945ghw495gwh495hw95w485

logging.level:
  web: debug
  sql: debug
  org.worker996.kotlinsprintbootpd: debug
  root: info